/**
 * Service detector (blueprint Part 2.3 + 11c).
 *
 * Scans the target app's `package.json` (dependencies + devDependencies)
 * and `.env.example` for patterns declared by each service manifest. Matches
 * are reported with full provenance so the installer can produce an
 * auditable detected-services.yaml (L2 — editable except provenance).
 *
 * Fallback behavior (11c):
 *   - default  → warn + skip: unknown deps/env vars are reported but don't
 *                block install.
 *   - strict   → fail-hard on any unknown prefix.
 *   - stubs    → emit a .yaml.stub draft manifest per unknown service (caller
 *                chooses whether to write them).
 */
import { promises as fs } from "node:fs";
import { join } from "node:path";
import yaml from "js-yaml";
import { loadServiceRegistry, type LoadedManifest } from "./registry-loader.js";
import type { ServiceManifest } from "../types.js";

export type DetectionMode = "default" | "strict" | "stubs";

export interface DetectedService {
  name: string;
  manifestPath: string;
  matchedPackagePatterns: string[];
  matchedEnvPatterns: string[];
  manifest: ServiceManifest;
}

export interface UnknownSignal {
  kind: "package" | "env";
  value: string;
  suggestedService?: string;
}

export interface DetectionReport {
  detected: DetectedService[];
  unknowns: UnknownSignal[];
  /** True iff strict mode and unknowns are present — installer aborts. */
  aborted: boolean;
  scannedPackageJson: boolean;
  scannedEnvExample: boolean;
}

export interface DetectInput {
  workingDir: string;
  registryDir: string;
  mode?: DetectionMode;
  /** Override registry load (tests). */
  manifestsOverride?: LoadedManifest[];
}

// ─── Main entry ───────────────────────────────────────────────────────────────

export async function detectServices(
  input: DetectInput,
): Promise<DetectionReport> {
  const mode = input.mode ?? "default";
  const manifests = input.manifestsOverride ?? (
    await loadServiceRegistry(input.registryDir)
  ).loaded;

  const pkgDeps = await readPackageJsonDeps(input.workingDir);
  const envKeys = await readEnvExampleKeys(input.workingDir);

  const detected: DetectedService[] = [];
  const matchedPkgs = new Set<string>();
  const matchedEnvs = new Set<string>();

  for (const { path, manifest } of manifests) {
    const matchedPackagePatterns = filterMatches(
      pkgDeps,
      manifest.detection.package_patterns,
      matchGlobLike,
    );
    const matchedEnvPatterns = filterMatches(
      envKeys,
      manifest.detection.env_patterns,
      matchGlobLike,
    );
    if (matchedPackagePatterns.length === 0 && matchedEnvPatterns.length === 0)
      continue;

    for (const dep of pkgDeps) {
      if (manifest.detection.package_patterns.some((p) => matchGlobLike(dep, p))) {
        matchedPkgs.add(dep);
      }
    }
    for (const env of envKeys) {
      if (manifest.detection.env_patterns.some((p) => matchGlobLike(env, p))) {
        matchedEnvs.add(env);
      }
    }

    detected.push({
      name: manifest.name,
      manifestPath: path,
      matchedPackagePatterns,
      matchedEnvPatterns,
      manifest,
    });
  }

  const unknowns: UnknownSignal[] = [];
  for (const dep of pkgDeps) {
    if (matchedPkgs.has(dep)) continue;
    if (!looksLikeKnownDep(dep)) continue;
    const suggestedService = suggestServiceForDep(dep);
    unknowns.push({
      kind: "package",
      value: dep,
      ...(suggestedService !== undefined ? { suggestedService } : {}),
    });
  }
  for (const env of envKeys) {
    if (matchedEnvs.has(env)) continue;
    if (!looksLikeKnownEnvPrefix(env)) continue;
    unknowns.push({ kind: "env", value: env });
  }

  const aborted = mode === "strict" && unknowns.length > 0;

  return {
    detected: detected.sort((a, b) => a.name.localeCompare(b.name)),
    unknowns,
    aborted,
    scannedPackageJson: pkgDeps.length > 0,
    scannedEnvExample: envKeys.length > 0,
  };
}

// ─── detected-services.yaml writer ────────────────────────────────────────────

export interface WriteDetectionInput {
  workingDir: string;
  report: DetectionReport;
}

export async function writeDetectedServicesYaml(
  input: WriteDetectionInput,
): Promise<string> {
  const out = {
    schema_version: 1,
    generated_at: new Date().toISOString(),
    services: input.report.detected.map((d) => ({
      name: d.name,
      installed_from_registry: d.manifestPath,
      matched_packages: d.matchedPackagePatterns,
      matched_envs: d.matchedEnvPatterns,
      status: d.manifest.status,
    })),
    unknowns: input.report.unknowns,
  };
  const path = join(
    input.workingDir,
    ".quality",
    "policies",
    "detected-services.yaml",
  );
  await fs.mkdir(join(path, ".."), { recursive: true });
  const preamble =
    "# GENERATED BY /playbook:install-qa-harness.\n" +
    "# Editable EXCEPT `installed_from_registry` (used for provenance audit).\n" +
    "# Rerun the installer with --upgrade to refresh.\n";
  await fs.writeFile(path, preamble + yaml.dump(out, { lineWidth: 120 }));
  return path;
}

export async function writeStubManifest(
  registryDir: string,
  unknown: UnknownSignal,
): Promise<string | null> {
  if (unknown.kind !== "package") return null;
  const name = normalizeDepToServiceName(unknown.value);
  if (!name) return null;
  const stubPath = join(registryDir, `${name}.yaml.stub`);
  try {
    await fs.access(stubPath);
    return stubPath; // already exists
  } catch {
    /* create below */
  }

  const stub = {
    name,
    display_name: name,
    category_hint: "business_logic",
    status: "stub",
    detection: {
      package_patterns: [unknown.value],
      env_patterns: [`${name.toUpperCase().replace(/-/g, "_")}_*`],
    },
    env_test_vars: { required: [], optional: [] },
    tier_hints: { critical_75: [], business_60: [], ui_gates_only: [] },
  };
  const preamble =
    "# STUB manifest generated by /playbook:install-qa-harness --stub-unknowns.\n" +
    "# Review + promote to .yaml before first use (set status: draft or validated).\n";
  await fs.mkdir(registryDir, { recursive: true });
  await fs.writeFile(stubPath, preamble + yaml.dump(stub));
  return stubPath;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

async function readPackageJsonDeps(workingDir: string): Promise<string[]> {
  const path = join(workingDir, "package.json");
  const raw = await fs.readFile(path, "utf8").catch(() => null);
  if (raw === null) return [];
  try {
    const pkg = JSON.parse(raw) as {
      dependencies?: Record<string, string>;
      devDependencies?: Record<string, string>;
      peerDependencies?: Record<string, string>;
      optionalDependencies?: Record<string, string>;
    };
    return Object.keys({
      ...pkg.dependencies,
      ...pkg.devDependencies,
      ...pkg.peerDependencies,
      ...pkg.optionalDependencies,
    }).sort();
  } catch {
    return [];
  }
}

async function readEnvExampleKeys(workingDir: string): Promise<string[]> {
  const candidates = [".env.example", ".env.local.example", ".env"];
  for (const name of candidates) {
    const path = join(workingDir, name);
    const raw = await fs.readFile(path, "utf8").catch(() => null);
    if (raw === null) continue;
    const keys: string[] = [];
    for (const line of raw.split("\n")) {
      const trimmed = line.trim();
      if (trimmed === "" || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq === -1) continue;
      const key = trimmed.slice(0, eq).trim();
      if (/^[A-Z][A-Z0-9_]*$/.test(key)) keys.push(key);
    }
    return keys;
  }
  return [];
}

function filterMatches(
  values: string[],
  patterns: string[],
  matcher: (value: string, pattern: string) => boolean,
): string[] {
  const out = new Set<string>();
  for (const pattern of patterns) {
    if (values.some((v) => matcher(v, pattern))) {
      out.add(pattern);
    }
  }
  return [...out];
}

/** Glob-like matcher: `*` within a segment, `?` single char. No path
 * separators matter since we apply to single identifiers (package names,
 * env var names). */
export function matchGlobLike(value: string, pattern: string): boolean {
  let re = "";
  for (let i = 0; i < pattern.length; i++) {
    const c = pattern[i];
    if (c === "*") re += ".*";
    else if (c === "?") re += ".";
    else if (/[.+^${}()|[\]\\]/.test(c as string)) re += `\\${c}`;
    else re += c;
  }
  return new RegExp(`^${re}$`).test(value);
}

/** Heuristic: a package name is "notable" (worth flagging as unknown service)
 * if it starts with `@` (scoped org), contains a known service hint word, or
 * ends with common SaaS suffixes. */
function looksLikeKnownDep(dep: string): boolean {
  if (dep.startsWith("@")) return true;
  const hints = [
    "auth", "db", "stripe", "pay", "mail", "email", "sms", "stream",
    "storage", "queue", "analytics", "cache", "redis", "kafka",
    "rabbitmq", "mongodb", "mysql", "postgres", "sentry", "log",
    "monitoring", "trace",
  ];
  return hints.some((h) => dep.toLowerCase().includes(h));
}

/** Heuristic: env var names are worth flagging if they look like a scoped
 * service prefix (2+ caps followed by _). */
function looksLikeKnownEnvPrefix(env: string): boolean {
  return /^[A-Z]{2,}_[A-Z]/.test(env) && !/^(NODE|NPM|CI|PATH|HOME|USER)/.test(env);
}

function suggestServiceForDep(dep: string): string | undefined {
  // Pull the first meaningful segment. "@vercel/postgres" → "vercel".
  const m = dep.match(/^@?([\w-]+)/);
  return m ? m[1] : undefined;
}

function normalizeDepToServiceName(dep: string): string | null {
  const simplified = dep.replace(/^@[^/]+\//, "").replace(/[^a-z0-9-]/gi, "-");
  if (!simplified) return null;
  return simplified.toLowerCase();
}
